extends RefCounted
# Snake-Man sound effects and music cues.
# rules.gd is generated by parse_snake_man.py and has no event bus, so this compares a
# snapshot of the rules before and after each frame and plays a sound for each change.
# The sounds match the web build's sfx.js; coat, pause and game over are new here.

const Chiptune := preload("res://chiptune.gd")

var synth: Chiptune
var song: Dictionary
var waka := false
var last: Dictionary = {}


func _init(chiptune: Chiptune, music: Dictionary) -> void:
	synth = chiptune
	song = music


func observe(r) -> void:
	var now := _take(r)
	if last.is_empty():
		last = now
		return
	var was := last
	last = now
	if now.mode != was.mode:
		_mode_changed(was, now)
	if now.mode != "play":
		return

	if now.eaten > was.eaten:
		if now.prism > was.prism + 100.0:
			synth.arp([660, 880, 1100, 1320], 0.05, Chiptune.Wave.TRI)
		else:
			waka = not waka
			synth.tone(520 if waka else 390, 260, 0.06, Chiptune.Wave.SQUARE, 0.5)

	if now.lives < was.lives:
		_hit()
	elif now.lives > was.lives:
		synth.arp([392, 523, 659, 784], 0.08, Chiptune.Wave.TRI)
	elif now.rung > was.rung:
		# Forage goal met at full lives: the points are banked instead.
		synth.arp([523, 659, 784, 1047, 1319], 0.06, Chiptune.Wave.TRI)
	elif now.invuln > was.invuln:
		# Bit yourself, or hit a wall while still invulnerable: moved, no life lost.
		synth.tone(140, 90, 0.1, Chiptune.Wave.SQUARE, 0.6)

	if now.stage > was.stage:
		synth.tone(200, 1200, 0.35, Chiptune.Wave.SAW, 0.35)

	if now.disguised and not was.disguised:
		synth.tone(500, 1000, 0.12, Chiptune.Wave.SINE, 0.45)
	elif was.disguised and not now.disguised:
		if now.coat_cool > r.busted_cool_ms() - 1000:
			# An immune ghost saw through the coat.
			synth.tone(1200, 400, 0.12, Chiptune.Wave.SAW, 0.5)
		else:
			synth.tone(1000, 500, 0.12, Chiptune.Wave.SINE, 0.35)

	if now.active.size() == was.active.size():
		var eaten_ghost := false
		var turned := false
		var sighted := false
		for i in now.active.size():
			eaten_ghost = eaten_ghost or (was.active[i] and not now.active[i])
			turned = turned or (now.traitor[i] and not was.traitor[i])
			sighted = sighted or (now.locked[i] and not was.locked[i])
		if eaten_ghost:
			synth.tone(1400, 180, 0.25, Chiptune.Wave.SQUARE, 0.6)
		if turned:
			synth.arp([330, 247], 0.08, Chiptune.Wave.SQUARE, 0.5)
		if sighted:
			synth.tone(900, 1300, 0.05, Chiptune.Wave.SINE, 0.4)


# Called with rules.dig()'s result, since a dig that fails changes nothing to compare.
func dug(ok: bool, mode: String) -> void:
	if mode != "play" and not ok:
		return
	if ok:
		synth.tone(180, 60, 0.18, Chiptune.Wave.TRI)
		synth.tone(80, 260, 0.15, Chiptune.Wave.TRI, 1.0, 0.16)
	else:
		synth.tone(140, 90, 0.1, Chiptune.Wave.SQUARE, 0.6)


func _hit() -> void:
	synth.tone(300, 60, 0.4, Chiptune.Wave.SAW)
	synth.tone(150, 40, 0.4, Chiptune.Wave.SQUARE, 0.5)


func _mode_changed(was: Dictionary, now: Dictionary) -> void:
	match now.mode:
		"play":
			if was.mode == "paused":
				synth.resume_music()
				synth.tone(880, 880, 0.06, Chiptune.Wave.SQUARE, 0.3)
			else:
				synth.play_music(song)
		"paused":
			synth.pause_music()
			synth.tone(660, 660, 0.06, Chiptune.Wave.SQUARE, 0.3)
		"over":
			synth.stop_music()
			var at := 0.0
			if now.lives < was.lives:
				_hit()
				at = 0.4
			synth.arp([392, 330, 262, 196], 0.16, Chiptune.Wave.SQUARE, 0.5, at)


func _take(r) -> Dictionary:
	var active: Array = []
	var traitor: Array = []
	var locked: Array = []
	for g in r.ghosts:
		active.append(g.active)
		traitor.append(g.traitor > 0)
		locked.append(g.locked)
	return {
		"mode": r.mode, "eaten": r.eaten, "prism": r.prism, "lives": r.lives, "rung": r.rung,
		"invuln": r.invuln, "disguised": r.disguised, "coat_cool": r.coat_cool, "stage": r.stage,
		"active": active, "traitor": traitor, "locked": locked,
	}
